Add project readme
yuji-2293/ColorMirror pull request #2
Opened 2024-12-07 08:01 UTC by yuji-2293

お世話になります
58期aの井上です
卒業制作用のアプリのREADME提出用のプルリクエストを作成しました
レビューのほどよろしくお願いします

2024-12-07 08:43 UTC, tarakish reviewed
確認しました。
> このサービスへの思い・作りたい理由、サービスの利用イメージ

ご自身がユーザー層に含まれるかと思いますが、実際に
「その日の気分にあった色を考え、その色と気圧の情報をもとにAIに提案された行動やコメントからポジティブな気持ちで過ごせるかどうか」は確認されてますでしょうか？（問題解決ができるかどうかの確認です）

2024-12-07 09:51 UTC, yuji-2293 commented
> 確認しました。
> 
> > このサービスへの思い・作りたい理由、サービスの利用イメージ
> 
> 
> 
> ご自身がユーザー層に含まれるかと思いますが、実際に
> 
> 「その日の気分にあった色を考え、その色と気圧の情報をもとにAIに提案された行動やコメントからポジティブな気持ちで過ごせるかどうか」は確認されてますでしょうか？（問題解決ができるかどうかの確認です）
> 
> 

お世話になります。
井上です
レビュー頂きありがとうございます。

AIでの確認行なっております。
例えば
「青、低気圧」
といったプロンプトを与えると
〈青い空を感じるとき、心は落ち着いているかもしれませんが、低気圧が影響している場合、体が重く感じたり、エネルギーが出にくくなることがあります。
提案: 青い空を見上げて心を落ち着けながら、今日は無理せず、静かな環境で過ごすのが良いでしょう。軽いストレッチや深呼吸で体をほぐし、必要なときは休息を取ってください。体調に合わせて、無理なく自分のペースを守りながら過ごすことが大切です。〉

色で心象風景を言語化、行動提案をもらうことで肯定的に1日を始められると考えてます。

2024-12-08 10:01 UTC, tarakish requested changes
ご確認ありがとうございます。
以下追加のコメントです！

---
- MVP
  - 差別化ポイントを考慮すると、天候情報を加味したAIのレスポンスはMVPとして提供されているとよいかと思いました。もし、本リリースでの実装に回した理由などがあればお伺いしたいです。

- 機能の実装方針予定
> React useStateで色選択の状態管理

こちらReactに関しては現時点でどの程度キャッチアップされていますか？
まだ十分でなければキャッチアップコストが高いため、Reactの導入は本リリース後の追加改修とし、一旦素のJavaScriptなどを使ってみてはいかがでしょうか？

2024-12-08 10:50 UTC, yuji-2293 commented
お世話になります！
コメントいただきありがとうございます！

 > * 最優秀選手   
>   * 差別化ポイントを考慮すると、天候情報を加味したAIのレスポンスはMVPとして提供されているとよいかと思いました。もし、本リリースでの実装に回した理由などがあればお伺いしたいです。
→こちらに関しては、気圧情報を持つAPIとAIを複合させる必要があると考えており、こちらに関してキャッチアップしながら実装になると思いリソース等の問題から本リリース後にさせてもらってました。
ただ、アプリの中核になる機能であると思うので、MVPで実装することが必須であるならばそうしようと思うのですがどう思われますでしょうか？

> > React useStateで色選択の状態管理
> こちらReactに関しては現時点でどの程度キャッチアップされていますか？ まだ十分でなければキャッチアップコストが高いため、Reactの導入は本リリース後の追加改修とし、一旦素のJavaScriptなどを使ってみてはいかがでしょうか？
→こちらに関しましては、先日モダンjavascriptの学習を開始したばかりとなっております。
浅知恵で見積もっておりましたが、MVPリリースに支障が来すようであれば本リリース後にしようと思います。

2024-12-09 08:44 UTC, tmtkzk0823 commented
> こちらに関しては、気圧情報を持つAPIとAIを複合させる必要があると考えており、こちらに関してキャッチアップしながら実装になると思いリソース等の問題から本リリース後にさせてもらってました。
ただ、アプリの中核になる機能であると思うので、MVPで実装することが必須であるならばそうしようと思うのですがどう思われますでしょうか？

READMEを拝見すると、アプリに「気候」が関わっていそうな印象を受けるので、こちらの機能はMVPに含める形がいいかと思いました。

> こちらに関しましては、先日モダンjavascriptの学習を開始したばかりとなっております。
浅知恵で見積もっておりましたが、MVPリリースに支障が来すようであれば本リリース後にしようと思います。

承知しました。
上記を踏まえた上でREADMEの変更をお願いします。

2024-12-09 09:23 UTC, ippei-shimizu commented
概ね良いかと思います。LGTMです。

2024-12-09 09:49 UTC, merged

2024-12-09 09:49 UTC, yuji-2293 commented
> 概ね良いかと思います。LGTMです。

ありがとうございました。
マージします